# Generated by Django 4.2.5 on 2023-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0002_customer_social_media_alter_interaction_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='social_media',
            field=models.URLField(default=''),
        ),
    ]
