# Generated by Django 4.2.5 on 2023-09-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0003_alter_customer_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='social_media',
            field=models.CharField(default='', max_length=200),
        ),
    ]
